import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const cfg=JSON.parse(read('config.json'));
const must=(cond,msg)=>{if(!cond)throw new Error(msg)};
const buy=(template,address)=>template.replace('{ca}',address);
must(cfg.network==='Robinhood Chain','network must be Robinhood Chain');
must(cfg.buyUrlTemplate==='https://ponsfamily.com/launchpad/{ca}','buy template mismatch');
must(buy(cfg.buyUrlTemplate,'ABC123')==='https://ponsfamily.com/launchpad/ABC123','ABC123 buy URL replacement failed');
must(buy(cfg.buyUrlTemplate,'XYZ999')==='https://ponsfamily.com/launchpad/XYZ999','XYZ999 buy URL replacement failed');
for(const f of ['app.js','bootstrap.js','token-artifact.js']) new vm.Script(read(f),{filename:f});
const html=read('index.html');
must(!/CA_GOES_HERE|YOUR_X_URL|YOUR_USERNAME|Lorem Ipsum|Update config\.json|Missing configuration|Configuration error|Development mode|stack trace/i.test(html),'index contains a prohibited visible marker');
for(const href of ['/docs','/privacy','/terms','/disclaimer','/cookies'])must(html.includes(`href="${href}"`),`missing link ${href}`);
for(const tool of ['token-creator','pons-v2','multisender','revoke','mint','burn','create-pool','add-liquidity','remove-liquidity','pause','unpause','block','unblock','token-page'])must(read('app.js').includes(`id:'${tool}'`),`missing tool ${tool}`);
must(!/charity/i.test(html+read('app.js')),'charity reference remains in the public app');
must(read('app.js').includes("tpl.replace('{ca}',ca)"),'dynamic {ca} replacement helper missing');
must(read('app.js').includes("path==='/docs'") && read('app.js').includes("path==='/privacy'") && read('app.js').includes("path==='/cookies'"),'route handlers missing');
console.log('QA passed');
